### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by Luc-Saccoccio** [aditya-K2/gomp#1]
Building the project works fine, but when running the executable, I get this message : 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x5b0a33]

goroutine 23 [running]:
gitlab.com/diamondburned/ueberzug-go.NewImage({0x0, 0x0}, 0x0, 0x0)
        /home/luc/.local/share/go/pkg/mod/gitlab.com/diamondburned/ueberzug-go@v0.0.0-20190521043425-7c15a5f63b06/ueberzug.go:25 +0x53
main.openImage({0xc0000e29c0, 0xc0000c04c0}, 0x1)
        /home/luc/repos/externals/goMP/render.go:45 +0x6c
created by main.(*Renderer).Start
        /home/luc/repos/externals/goMP/render.go:63 +0x8f
```
(The repository is cloned at `/home/luc/repos/externals`)

**Comment by daveriedstra** [comment]
I just ran into this and discovered that "~" is not expanded properly in the path to the default image. Might be worth a note in the README and maybe checking to make sure the behaviour is consistent with the other config paths.

**Comment by aditya-K2** [comment]
> I just ran into this and discovered that "~" is not expanded properly in the path to the default image. Might be worth a note in the README and maybe checking to make sure the behaviour is consistent with the other config paths.

I see. I will add this to the README.
