### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by DavidHenryThoreau** [aditya-K2/gomp#14]
Steps to build the latest version :
1/ go build on master branch
2/ get default version https://github.com/aditya-K2/goMP/blob/master/sample_config.yml to .config/$USER/goMP/config.yml and change MUSIC_DIRECTORY

The program needs a local mpd configuration file :
`No config File for mpd Found
panic: open $USER/.config/mpd/mpd.conf: no such file or directory`
but i'm using config file at /etc/mpd.conf (why not add an option to set config file path ?)

```
./goMP
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x78d5fb]

goroutine 3 [running]:
main.getImagePath({0xc0000280c6, 0x38})
        /home/user/goMP/render.go:94 +0x5bb
main.openImage({0xc0000280c6, 0x38}, 0x0)
        /home/user/goMP/render.go:47 +0x6f
created by main.(*Renderer).Start
        /home/user/goMP/render.go:67 +0x8f
```

**Comment by aditya-K2** [comment]
have you defined cache directory?

**Comment by aditya-K2** [comment]
https://github.com/aditya-K2/goMP#setting-up-cache-directory-and-cache-file

**Comment by aditya-K2** [comment]
I have updated the sample config to setup the cache directory

**Comment by aditya-K2** [comment]
> but i'm using config file at /etc/mpd.conf (why not add an option to set config file path ?)

when it doesn't find mpd.conf goMP panics https://github.com/aditya-K2/goMP/blob/51794d6324d82d0c3a9d8215709e377eec6f154f/config/config.go#L56

I think I will change the behaviour and make it check the config file.

**Comment by DavidHenryThoreau** [comment]
I now can open goMP :)
I'm using music directory like this : 
- Artist
   Album
   file1.mp3
   file2.mp3
   cover.jpg

Cover are not in CACHE_FILE.
Does goMP can extract on the fly cover for mp3 idtag file ?
Does goMP can get cover.jpg or anything else file located in MUSIC_DIRECTORY ?

**Comment by aditya-K2** [comment]
> Does goMP can extract on the fly cover for mp3 idtag file ?

yeah goMP extracts on the fly and copies the image to the CACHE_DIR and writes the path to the image in the CACHE_FILE
for e.g 

let's say you play a song named `foo` by artist `bar` from album `doe`  then the cache file will contain the following entry

```
#  artist    album   path to extracted image
bar     doe    CACHE_DIR/bar_doe.png   # Here album and artist have been stored as songs from the same album will have the same album cover
``` 
maintaining a cache file has one advantage for the albums which didn't have embedded cover art and last fm info we can point the path to the default image without copying it 

I am currently working on a better method to cache it is almost done, which solves a major issue with the above method as the cache file is loaded in memory buffer and written to file after closing the app, the times when the goMP isn't closen and the user poweroff's the computer or unexpected closing of terminals lead to some side effects

**Comment by aditya-K2** [comment]
> Does goMP can get cover.jpg or any other picture file (png,jpeg) located in MUSIC_DIRECTORY ?

Currently, no.
this feature was discussed in #2 too. I will add this soon.

**Comment by aditya-K2** [comment]
> In goMP i can't see the cover, they are not in CACHE_FILE folder.

Have you defined both the `CACHE_DIR` and `CACHE_FILE` 

CACHE_DIR is where the image will be stored
and CACHE_file will contain the references for all the extracted images.

**Comment by aditya-K2** [comment]
can you please drop your config.yml. And thanks for reporting the issues 🫂

**Comment by aditya-K2** [comment]
I think you might want to add a / in the end of the CACHE_DIR 

for e.g if your CACHE_DIR was `/home/user/goMPcache`

then make it `/home/user/goMPcache/`
