### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by johnallen3d** [aditya-K2/gomp#26]
I haven't had any success getting `gomp` to run to this point. I decided to try troubleshooting a little bit and have a slightly better understanding of why now. It looks like `Notify` is `nil` when `GetImagePath` is executed.

I added `fmt.Println(Notify)` [here](https://github.com/aditya-K2/gomp/blob/6c2458b320e59f82c5c107d08f99a11a41d63b51/render/render.go#L104) and this is what I see.

```shell
$ go build && ./gomp
<nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x13a10ea]

goroutine 4 [running]:
github.com/aditya-K2/gomp/render.GetImagePath({0xc0000280f6, 0x3e})
	/Users/johna/tmp/gomp/render/render.go:106 +0x38a
github.com/aditya-K2/gomp/render.OpenImage({0xc0000280f6, 0x3e}, 0x0?)
	/Users/johna/tmp/gomp/render/render.go:59 +0x6f
created by github.com/aditya-K2/gomp/render.(*Renderer).Start
	/Users/johna/tmp/gomp/render/render.go:79 +0x8a
```

Unfortunately, I have _*very*_ little experience with Go, otherwise, I'd try to troubleshoot further.

Some further information. I'm running on macOS and building from source. I'm using Kitty and not really expecting imagine rending to work at this point.

**Comment by daveriedstra** [comment]
Hi I experience the same thing on linux (Pop OS) using kitty. I do regularly use kitty's image rendering with nnn, not sure if that's relevant. Unfortunately I don't have a ton of time to dig into this but I'd be happy to test if that helps.

```
❯ ./gomp 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7a68ec]

goroutine 10 [running]:
github.com/aditya-K2/gomp/render.GetImagePath({0xc0000284d6, 0x66})
	/home/dried/Software/gomp/render/render.go:104 +0x42c
github.com/aditya-K2/gomp/render.OpenImage({0xc0000284d6, 0x66}, 0x1?)
	/home/dried/Software/gomp/render/render.go:58 +0x6f
created by github.com/aditya-K2/gomp/render.(*Renderer).Start
	/home/dried/Software/gomp/render/render.go:78 +0x8a
```

**Comment by aditya-K2** [comment]
> Some further information. I'm running on macOS and building from source. I'm using Kitty and not really expecting imagine rending to work at this point.

The library that renders the images uses child windows  of X Server for rendering the images, maybe that might  be the problem. But I have tried changing the code, and start the renderer after the Notification server starts. 

The commit is made on the `iss26` branch

```bash
git pull origin iss26
git checkout iss26
go build 
```

**Comment by johnallen3d** [comment]
I can confirm that this runs without crashing, thanks!
