### ISSUE TITLE
gomp panic: invalid memory address

### ISSUE THREAD

**Issue by ignition-ctrl** [aditya-K2/gomp#33]
Just found this project, looks interesting. Installed it from aur, but ran into this error. 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x563de28a0cf3]

goroutine 6 [running]:
gitlab.com/diamondburned/ueberzug-go.NewImage({0x0, 0x0}, 0x0?, 0x0?)
	gitlab.com/diamondburned/ueberzug-go@v0.0.0-20190521043425-7c15a5f63b06/ueberzug.go:25 +0x53
github.com/aditya-K2/gomp/render.OpenImage({0xc000165946, 0x3a}, 0x0?)
	github.com/aditya-K2/gomp/render/render.go:52 +0x110
created by github.com/aditya-K2/gomp/render.(*Renderer).Start
	github.com/aditya-K2/gomp/render/render.go:70 +0x8a
```
Cloned the git repo, built it from there, same error. Then I checked out to an earlier commit. Same error. Seems it might be something on my side. 
Here is my config.yml
```
MPD_PORT : "6600"
MUSIC_DIRECTORY : "~/Music"
DEFAULT_IMAGE_PATH : "~/Pictures/defaultlain.jpg"
SEEK_OFFSET : 5
CACHE_DIR : "~/.config/gomp/cache"
#GET_COVER_ART_FROM_LAST_FM : "TRUE"
#LASTFM_API_KEY : "4e316e10a94a2eef30b605fc3db04cf1"
#LASTFM_API_SECRET : "d95f07d336316312a81e34680c6d5bb2"
```
Please advise. Also, sorry for making an empty issue and then editing it later. Was about to type this up when I misclicked and then something came up.

**Comment by ignition-ctrl** [comment]
It seems like it's something wrong with ueberzug getting the image boundaries in ueberzug.go

**Comment by aditya-K2** [comment]
As mentioned [here](https://github.com/aditya-K2/gomp/blob/6830b5379fab3a413a7e260d903f0f6e686e1ff4/sample_config.yml#L97) You have to provide the path to directories by expanding the `~` to `/home/your_user_name`

**Comment by aditya-K2** [comment]
I think it's about time I add an internal check as most of the time we use `~`.

**Comment by ignition-ctrl** [comment]
Yep that was it. Thanks for the help. Working now.

**Comment by Felix-Kyun** [comment]
so for commenting here instead of making a new issue,
i ran into the same issue today even after using absolute path in config.
this was the error
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x563041d225d3]

goroutine 20 [running]:
gitlab.com/diamondburned/ueberzug-go.NewImage({0x0, 0x0}, 0x0?, 0x0?)
	gitlab.com/diamondburned/ueberzug-go@v0.0.0-20190521043425-7c15a5f63b06/ueberzug.go:25 +0x53
github.com/aditya-K2/gomp/render.OpenImage({0xc0003d45f6, 0x48}, 0x0?)
	github.com/aditya-K2/gomp/render/render.go:52 +0x110
created by github.com/aditya-K2/gomp/render.(*Renderer).Start
	github.com/aditya-K2/gomp/render/render.go:70 +0x8a
```

my config
```yml
MPD_PORT : "6600"
MUSIC_DIRECTORY : "/home/felix/Media/music/"
SEEK_OFFSET : 5
CACHE_DIR : "/home/felix/.config/gomp/.cache"
```

thank you.

**Comment by aditya-K2** [comment]
have you tried updating gomp?

**Comment by aditya-K2** [comment]
> my config
> 
> ```yaml
> MPD_PORT : "6600"
> MUSIC_DIRECTORY : "/home/felix/Media/music/"
> SEEK_OFFSET : 5
> CACHE_DIR : "/home/felix/.config/gomp/.cache"
> ```

There is no need now to provide Absolute path `gomp` now expands `~` to user's Home Directory. Have you created `.cache` in `.config/gomp/` ?

**Comment by aditya-K2** [comment]
If you haven't created `.cache` , then `gomp` looks for `DEFAULT_IMAGE_PATH` as you haven't provided that there is no image to fallback on. so please provide `DEFAULT_IMAGE_PATH`.

**Comment by Felix-Kyun** [comment]
> If you haven't created `.cache` then `gomp` looks for `DEFAULT_IMAGE_PATH`. As you haven't provided it there is no image to fall back on. so please provide `DEFAULT_IMAGE_PATH`.

so even with `.cache` i need to define `DEFAULT_IMAGE_PATH` or as long as i have the `.cache` dir, its not needed ?

**Comment by aditya-K2** [comment]
Please provide `DEFAULT_IMAGE_PATH` in config.yml

**Comment by Felix-Kyun** [comment]
> have you tried updating gomp?

i had just installed `-git` from aur that time so yea it should be the latest

**Comment by aditya-K2** [comment]
> > If you haven't created `.cache` then `gomp` looks for `DEFAULT_IMAGE_PATH`. As you haven't provided it there is no image to fall back on. so please provide `DEFAULT_IMAGE_PATH`.
> 
> so even with `.cache` i need to define `DEFAULT_IMAGE_PATH` or as long as i have the `.cache` dir, its not needed ?

Basically If gomp doesn't find any cover art (embedded or from last fm) it falls back to the default image.

**Comment by aditya-K2** [comment]
> ![2022-10-20-210308_1360x765_scrot](https://user-images.githubusercontent.com/99094581/196993220-6603a3d7-11ef-4db8-8198-1a6cdee7905e.png)

as of right now gomp doesn't support webp images. Please use jpg image. I am sorry for the inconvenience.

**Comment by Felix-Kyun** [comment]
looks like using a .png file fixed it. thank you

**Comment by Felix-Kyun** [comment]
btw i just noticed, even though i have my audio files have embedded album art but it still shows the default album art, am i missing somthing ?

**Comment by aditya-K2** [comment]
> btw i just noticed, even though i have my audio files have embedded album art but it still shows the default album art, am i missing somthing ?
> 

Weird. Does It happen for all songs or just for somd of them?

**Comment by Felix-Kyun** [comment]
> for all songs or just for some of them? Can you open a new issue?

sure
