### ISSUE TITLE
while opening sometime the album art covers the whole screen and a restart is needed to fix it 

### ISSUE THREAD

**Issue by Felix-Kyun** [aditya-K2/gomp#39]
https://user-images.githubusercontent.com/99094581/197354298-2f95447f-c203-4e62-9faf-2e1d1fe68e7c.mp4

**Comment by aditya-K2** [comment]
I am aware of this effect. I am working on the fix. Basically what happens is that sometimes the cover art gets rendered before the UI is drawn. Expect a commit soon.
