### ISSUE TITLE
[Request] Release binaries on github

### ISSUE THREAD

**Issue by m040601** [aditya-K2/gomp#57]
Thanks for your work on this tool.

I'm a long time cli mpd clients user (ncmpcpp).
Just heard about gomp in the Arch linux forums.

I'm eager to try it out.
We do already have a "recipe" called PKGBUILD for building it on Archlinux. Either the "release" version or the "git" version.

https://aur.archlinux.org/packages/gomp or https://aur.archlinux.org/packages/gomp-git

I just dont want to download 500 Mega of Go just to compile it.
Especially in tiny ARM devices which are perfect for running mpd and/or a cli client.
Ex. Raspberry Pi (aarch64 or armv7h) or chromebooks.

Since it is written in Go, and github makes it easy and free to release binaries with automated github workflows for many different architectures

This would also make it very easy for package maintainers of different Linux distros to create a "gomp-bin" version for their distro that basicly just pulls the binary from github.

It's what many "famous" and  popular go github projects do.

See for example how,

https://github.com/junegunn/fzf
https://github.com/gokcehan/lf

do it.

Thanks in advance.

**Comment by aditya-K2** [comment]
Hi, thanks for suggesting this. My other project, [gspt](https://guthub.com/aditya-k2/gspt), does provide binaries for different architectures I will port the make file for gomp too.

**Comment by aditya-K2** [comment]
Hi! The release now has binaries for multiple architectures. Please feel free to suggest any architectures that are missing. Thanks!
