### ISSUE TITLE
Files Section Not Working And No Help Text.

### ISSUE THREAD

**Issue by atikattar1104** [aditya-K2/gomp#59]
As Someone New In Linux, I Never Managed To Find How To Use Gomp. But Upon Experimenting, I Managed To Figure Out Some Keys To Use. 

Also My Songs Directory Is Same Mentioned In MPD Configs And In Gomp Configs. Yet Songs Cannot Be Played. 

Note :- Using In Termux. Android 10 MIUI 12.5

**Comment by aditya-K2** [comment]
Gomp's navigation is very similar to ranger (the terminal file manager). Gomp uses the vim keys (h, j, k, l) for navigation and 1, 2, 3 to change the views. h, l are used to change where you are in the directory tree ( `l` takes you one level down as in shows the children of the selected directory or plays it if it's a file, `h` brings you one level back )
