### ISSUE TITLE
Album art not displaying, fallback image also not displaying.

### ISSUE THREAD

**Issue by TheCodeOfCaleb** [aditya-K2/gomp#60]
Hi, I am trying out gomp for the first time. I used the example config and was able to connect to my server no problem, the only thing I changed was disabling lastfm art downloading as my files should have images embedded. Upon launching, no image (not even a preview image) is displayed, and a message pops up in the corner that simply says "Error Rendering Image!".

My terminal emulator is Alacritty. I suspect the issue has something to do with my terminal emulator configuration, but I couldn't find anything online about enabling image rendering in Alacritty, and I couldn't find anything in the gomp documentation about extra steps/ troubleshooting to get images to show up. If anyone has any experience or suggestions it would be appreciated, and let me know if you need other information.

![image](https://github.com/aditya-K2/gomp/assets/17418894/96126aef-4ae5-4e6a-8b22-e0987ee998a1)

**Comment by TheCodeOfCaleb** [comment]
Actually, I was mistaken about the default/ fallback image, I hadn't set it up correctly. So i am now displaying a fallback image, but actual album art still won't render.

**Comment by aditya-K2** [comment]
Hi sorry for the late reply. Are you still facing this issue?

**Comment by teleothleo** [comment]
> Hi sorry for the late reply. Are you still facing this issue?

I am facing sth similar.. Every time I open gomp..

![1713872329](https://github.com/aditya-K2/gomp/assets/18376458/04b4a9f2-c0cf-4229-82f4-5f5aade0778c)

**Comment by aditya-K2** [comment]
> > Hi sorry for the late reply. Are you still facing this issue?
> 
> I am facing sth similar.. Every time I open gomp.. The cover art is located inside the folder with `.mp3` files, is named `cover.jpg`, is `1.8MiB` and has dimensions of `1437px x 1413px`
> 
> ![1713872329](https://private-user-images.githubusercontent.com/18376458/324815351-04b4a9f2-c0cf-4229-82f4-5f5aade0778c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NzMyNDIsIm5iZiI6MTcxMzk3Mjk0MiwicGF0aCI6Ii8xODM3NjQ1OC8zMjQ4MTUzNTEtMDRiNGE5ZjItYzBjZi00MjI5LTgyZjQtNWY1YWFkZTA3NzhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDE1MzU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyNzFjNDlkYmM3MTEwMGQ2YmI0ZjQ5ZWFjNDU3MTA3MmNjY2Q0NzBkMGFkYzc3MTQxZTE2MjQwNjRjNGViOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LN7o8Hi8sKgfTxJAiIwT3q0n8Um3gILkgL4_jbvFrAA)

Is the default image displayed? This might be because there is no embedded image in the music, gomp doesn't really look into the file's directory for the `cover.jpg` or any image for that matter.

**Comment by aditya-K2** [comment]
@TheCodeOfCaleb  @teleothleo . Can you please check with the latest build of gomp. It should be fixed now.
