### ISSUE TITLE
Image Conversion Logging Breaks TUI

### ISSUE THREAD

**Issue by LennyPhoenix** [aditya-K2/gomp#63]
Certain album covers which use atypical colour encoding (e.g. grayscale) can cause messages to be logged to stdout, which leads to strange visual bugs and issues rendering the TUI correctly.

![image](https://github.com/aditya-K2/gomp/assets/57148878/5e0a2a67-2763-4722-8ff1-696a7c528282)

![image](https://github.com/aditya-K2/gomp/assets/57148878/8feac7d7-2056-4aaa-be49-f726d74c968c)

"Converting image type *image.Gray the slow way. Optimization for this image type hasn't been added yet."

**Comment by aditya-K2** [comment]
This is a log from the [xgbutil library](https://github.com/BurntSushi/xgbutil/blob/ad855c7130460fb6cf40af9302c649a69082a4ee/xgraphics/new.go#L54). And only seems to occur with black and white images. There's nothing that in gomp that can be changed to fix this logging (Maybe try changing the xgbutil.Logger to a custom logger, will have to test the implications of this). Closing this for now. Thanks for reporting!
