### ISSUE TITLE
Possible Wayland incompatibility

### ISSUE THREAD

**Issue by faustseele** [aditya-K2/gomp#65]
OS version: 6.9.8.arch1-1
Window system: **Wayland**

I get this output when trying to launch gomp:

```
Error Occured While getting font width: BadDrawable {NiceName: Drawable, Sequence: 8, BadValue: 0, MinorOpcode: 0, MajorOpcode: 14}
```

The app flashes for a split-second and disappears.
Both ttf-dejavu & noto-fonts are installed, if it's important.

**Comment by faustseele** [comment]
The config it the default one from [here](https://github.com/aditya-K2/gomp/blob/master/docs/_config.yml)

**Comment by danielwerg** [comment]
Originally I installed `gomp-bin` but cover art wasn't displaying (https://github.com/aditya-K2/gomp/issues/60) now after  switching to `gomp-git` I'm facing same issue. And only after writing this I saw https://github.com/aditya-K2/gomp?tab=readme-ov-file#things-to-note ;D

> Images are rendered using the X child windows. Currently there is no support for Wayland.

**Comment by akurdunkar** [comment]
There is no support for wayland currently. Closing the issue.
